### ISSUE TITLE
Property "type" in `OrganizationalUnitReference` is ambiguous, because "type" is a reserved word

### ISSUE THREAD

**Issue by kvakes** [windingtree/org.json-schema#14]
```yaml
  OrganizationalUnitReference:
    description: Organizational unit
    type: object
    required:
      - name
      - media
    properties:
      name:
        description: >-
          Unit name e.g. "Grand Budapest Hotel", "Accounting Department"
          or "Acme 13th Ave"
        type: string
      type:
        description: Unit type, e.g. ["hotel", "boutique"]
        type: array
        items:
          allOf:
            - type: string
```
